# Định nghĩa tên workflow
name: CI/CD Pipeline (Test)

# Các biến môi trường
env:
  NODE_ENV: production
  MAIN_BRANCH: main
  STAGING_BRANCH: staging
  DEVELOP_BRANCH: develop

# Kích hoạt workflow
on:
  push:
    branches:
      - main
      - staging
      - develop
  pull_request:
    branches:
      - main

# Jobs định nghĩa các bước trong pipeline
jobs:
  # Job 1: Kiểm tra, build và test ứng dụng
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      # Bước 1: Checkout code từ repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Bước 2: Thiết lập Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.17.0

      # Bước 3: Cài đặt dependencies
      - name: Install dependencies
        run: sudo npm install
        # run: npm ci # Dùng npm ci để cài đặt dependencies từ package-lock.json

      # Bước 4: Chạy kiểm thử
      # - name: Run tests
      #   run: npm test
      # Bước 4: Kiểm tra Node.js version (tuỳ chọn)
      - name: Check Node.js version
        run: node -v

      # Bước 5: Build ứng dụng
      - name: Build application
        run: sudo npm run build

  # Job 2: Deploy ứng dụng
  deploy:
    runs-on: ubuntu-latest
    needs: build_and_test
    steps:
      # Bước 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Bước 2: Triển khai ứng dụng (ví dụ sử dụng SSH)
      - name: Deploy application
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        run: |
          echo "Deploying branch: ${{ github.ref_name }} - ${ CI_JOB_TOKEN }"
          case "${{ github.ref_name }}" in
            "${MAIN_BRANCH}")
              echo "Deploying to Production";;
            "${STAGING_BRANCH}")
              echo "Deploying to Staging";;
            "${DEVELOP_BRANCH}")
              echo "Deploying to Development";;
            *)
              echo "Unknown branch: ${{ github.ref_name }}";;
          esac
